### PR TITLE
Close channel if `HTTP2ServerConnectionManager.StateMachine.streamClosed() returns close

### LINKED ISSUE #721: Hummingbird can get stuck during graceful shutdown when running with http/2
Hummingbird gets stuck during graceful shutdown when running with http/2, if the graceful shutdown signal comes during a request.

### Logs:
```
2025-06-20T22:05:34+0100 info Test : port=12345 [ADS] Starting server as PID 82493

2025-06-20T22:05:34+0100 debug Test : sl-cancellationSignals=[] sl-gracefulShutdownSignals=[SIGINT] sl-services=[Application] [ServiceLifecycle] Starting service lifecycle

2025-06-20T22:05:34+0100 debug Test : sl-service=Application [ServiceLifecycle] Starting service

2025-06-20T22:05:34+0100 debug Test : sl-cancellationSignals=[] sl-gracefulShutdownSignals=[] sl-services=[Hummingbird.DateCache, PreludeService<Server<HTTP2UpgradeChannel>>] [ServiceLifecycle] Starting service lifecycle

2025-06-20T22:05:34+0100 debug Test : sl-service=Hummingbird.DateCache [ServiceLifecycle] Starting service

2025-06-20T22:05:34+0100 debug Test : sl-service=PreludeService<Server<HTTP2UpgradeChannel>> [ServiceLifecycle] Starting service

2025-06-20T22:05:34+0100 trace Test : [HummingbirdCore] Server State: starting

2025-06-20T22:05:34+0100 info Test : [HummingbirdCore] Server started and listening on 0.0.0.0:12345

2025-06-20T22:05:34+0100 trace Test : [HummingbirdCore] Server State: running

^C2025-06-20T22:05:41+0100 debug Test : sl-signal=SIGINT [ServiceLifecycle] Signal caught. Shutting down the group.

2025-06-20T22:05:41+0100 debug Test : sl-service=Application [ServiceLifecycle] Triggering graceful shutdown for service

2025-06-20T22:05:41+0100 debug Test : [ServiceLifecycle] Graceful shutdown caught. Cascading shutdown to services

2025-06-20T22:05:41+0100 debug Test : sl-service=PreludeService<Server<HTTP2UpgradeChannel>> [ServiceLifecycle] Triggering graceful shutdown for service

2025-06-20T22:05:41+0100 trace Test : [HummingbirdCore] Server State: shuttingDown
```

### To reproduce

Run a http2 server with a single endpoint. In that endpoint, sleep for some time. Make a request to the server and then and press ctrl-c during the sleep. The server hangs forever, even after the request completes. Pressing ctrl-c further after this point continues to have no effect.

Pressing ctrl-c for the first time when a request in not in flight results in shutdown as expected.

[full repro example.zip](https://github.com/user-attachments/files/20977112/hb.shutdown.issue.repro.zip)

### Impact

A http/2 server cannot be shutdown gracefully unless you’re lucky enough to send the sigint when there happens to be no request in flight.

### PR DESCRIPTION
**Pull request by adam-fowler**
Previously we were triggering a graceful shutdown when receiving a close action from `HTTP2ServerConnectionManager.StateMachine.streamClosed()`. This was incorrect as we are already in graceful shutdown and have sent the second goaway so we should close the connection.

This should fix #721

### CODE REVIEW

**Comment by adam-fowler** [comment]
I also fix the typo reported in #722

File: Tests/HummingbirdHTTP2Tests/HTTP2Tests.swift [hunk 1]
```diff
@@ -243,4 +244,54 @@ final class HummingBirdHTTP2Tests: XCTestCase {
...
+
+                group.addTask {
+                    try await serviceGroup.run()
+                }
+
+                let port = await promise.wait()
+                group.addTask {
+                    let request = HTTPClientRequest(url: "https://localhost:\(port)/")
+                    let response = try await httpClient.execute(request, deadline: .now() + .seconds(30))
+                    XCTAssertEqual(response.status, .ok)
```
Comment (Joannis) [inline Tests/HummingbirdHTTP2Tests/HTTP2Tests.swift:289]: How do we know this test runs on H2?

Comment (adam-fowler) [reply Tests/HummingbirdHTTP2Tests/HTTP2Tests.swift:289]: As I said on discord it isn't that easy to verify the upgrade occurred. All the HTTP2 tests suffer from that. I have verified in the debugger. Can we push that verification to another PR?

**Review by Joannis — APPROVED** [review]
